### ISSUE TITLE
move device_params under connection_options>netconf>extras

### ISSUE THREAD

**Issue by slinkish** [h4ndzdatm0ld/nornir_netconf#40]
https://github.com/h4ndzdatm0ld/nornir_netconf/blob/9ab5316af01e7824d2edcc330ef194c60b10ff6e/nornir_netconf/plugins/connections/netconf.py#L108

Trying to migrate from nornir 2.5 to 3.x with this plugin. Builtin netconf connection did not use host.platform in the ncclient manager. I have more application logic built around host.platform and names are not compatible with ncclient's devices. Would you be willing to consider moving this data to connection_options>netconf>extras to be more consistent with other ncclient parameters?

**Comment by h4ndzdatm0ld** [comment]
Hey there @slinkish  - Sorry I missed this issue. I will take a look! Thanks for the feedback

**Comment by slinkish** [comment]
Hey thanks yeah still waiting on the final verdict. No other issues other than the if platform statement. For the netconf based devices it makes the host.platform values a subset of the ncclient device handlers which is a bit too restrictive. No modification needed to have device_params inside extras with line 115 parameter update call. Respect that this change most likely breaks your work flow, perhaps some boolean flag in extras that can be used as the conditional to match host.platform with device_params and then you only have to modify a single group to achieve the same functionality?

**Comment by h4ndzdatm0ld** [comment]
Hey @slinkish  Do you want to take a stab at submitting a PR?

**Comment by slinkish** [comment]
Sure, will try to play around with the integration tests to see if I can better clarify the change.

**Comment by h4ndzdatm0ld** [comment]
Hey, I just finally took some time to dig into this and try it. See the example below. Without modification, this should work. `extras` gets unpacked as you pointed out, so if you omit from passing in `platform` at the higher level, but pass in 'name' as the key and the platform name as the value, it should work. 

Do you mind trying that out?

```
sros:
  username: "admin"
  password: "admin"
  port: 830
  # platform: "sros"  <--- example of where to comment out platform
  connection_options:
    netconf:
      extras:
        hostkey_verify: false
        timeout: 300
        allow_agent: false
        look_for_keys: false
        device_params: <-- add device_params dict
          name: "sros" < -- the key is name, the value is platform
```
